scrabbly_cloud/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from settings import MEDIA_ROOT
from django_tweak.urls_manager import UrlsManager

import scrabblycloud.views as views_root

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': True}),
)

UrlsManager(urlpatterns, views_root)

scrabbly_cloud/scrabblycloud/models.py
from django.db import models
from django.contrib.auth.models import User


class Tile(models.Model):

    x = models.PositiveIntegerField(null=True)
    y = models.PositiveIntegerField(null=True)
    letter = models.CharField(max_length=1)


class Player(models.Model):

    user = models.ForeignKey(User)

    name = models.CharField(max_length=500)
    remote_id = models.CharField(max_length=100)    

    def picture(self):

        return "https://graph.facebook.com/%s/picture" % self.remote_id


class PlayerBoard(models.Model):

    player = models.ForeignKey("Player")
    board = models.ForeignKey("Board")    

    points = models.PositiveIntegerField(default=0)
    tiles = models.ManyToManyField("Tile", null=True, blank=True)


class Board(models.Model):

    tiles = models.ManyToManyField('Tile', null=True, blank=True)
    players = models.ManyToManyField('Player', through="PlayerBoard")

    height = models.PositiveIntegerField()
    width = models.PositiveIntegerField()
    turn = models.ForeignKey("Player", null=True, blank=True, related_name="player_turn")

scrabbly_cloud/scrabblycloud/views/base.py
from django.views.generic import TemplateView
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseServerError
import simplejson as json

from django.template.loader import get_template
from django.template import Context
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

from settings import HOST, FACEBOOK_CONFIG


class BaseView(TemplateView):

    login_exempt = True
    csrf_exempt = True

    def dispatch(self, request, *args, **kwargs):

        return TemplateView.dispatch(self, request, *args, **kwargs)

    def redirect(self, url):

        return HttpResponseRedirect(url)

    def response(self, response):

        return HttpResponse(response)

    def response_error(self, response):

        return HttpResponseServerError(response)

    def json_response(self, response):

        return self.response(json.dumps(response))

    def render(self, template, context):

        return get_template(template).render(Context(context))

    def get_list_args(self, startswith):

        return [key[len(startswith):] for key, value in self.request.POST.iteritems() if key.startswith(startswith)]

    def get_params(self, data, params):

        dict_params = {}
        for param in params:
            dict_params[param] = data.get(param)
        return dict_params

    def render_to_response(self, context):

        context["FB_APP_ID"] = FACEBOOK_CONFIG["id"]
        context["HOST"] = HOST
        return TemplateView.render_to_response(self, context)

    def get_current_player(self):

        return self.request.user.get_profile()


class AjaxBaseView(BaseView):

    def on_success(self):

        return self.json_response({"status": "ok"})

    def on_fail(self, error):

        return self.json_response({"status": "fail", "error": error})


class AjaxSaveBaseView(AjaxBaseView):

    def after_save(self, entity):

        pass

    def post(self, *args, **kwargs):

        try:
            entity = self.service.save(self.request)
            self.after_save(entity)
            return self.render(self.on_success)

        except ValidationError, e:
            return self.render(self.on_fail, str(e))

    def render(self, function, *args, **kwargs):

        return self.response(function(*args, **kwargs))


class AjaxFormSaveBaseView(AjaxSaveBaseView):

    def get_data(self, request):

        return request.POST

    def post(self, *args, **kwargs):

        form = self.form(self.get_data(self.request), *args, **kwargs)

        if (form.is_valid()):
            form.save()
            return self.render(self.on_success)

        return self.render(self.on_error, **form.errors)

    def on_error(self, **data):

        return self.json_response(data)


class CachedView(BaseView):

    @method_decorator(cache_page(60 * 60))
    def dispatch(self, request, *args, **kwargs):
        return super(BaseView, self).dispatch(request, *args, **kwargs)


class ValidationError(Exception):

    pass

scrabbly_cloud/scrabblycloud/views/board.py
import simplejson as json
from base import BaseView

from scrabblycloud.services.board import BoardService
from scrabblycloud.services.game import ScrabblyService


class BaseBoardView(BaseView):

    service = BoardService()


class BoardsView(BaseBoardView):    

    url = "^boards$"

    def render_to_response(self, context):
        
        context["boards"] = self.service.all()
        return BaseView.render_to_response(self, context)


class BoardView(BaseBoardView):

    url = "^boards/(?P<board_id>\d+)/$"

    def render_to_response(self, context):

        board_model = self.service.get_object_or_404(id=self.kwargs["board_id"])
        board, player_board = ScrabblyService().new(board_model, self.get_current_player())

        context = {"board": board_model, "player_board": player_board }
        context["tiles"] = BoardService().get_tiles(board_model)
        context["is_player_turn"] = self.service.is_player_turn(self.get_current_player(), board_model)

        return BaseView.render_to_response(self, context)


class PlayView(BaseBoardView):
    
    def post(self, *args, **kwargs):

        data = self.request.POST["letters"]
        tiles = json.loads(data)

        board = self.service.get(id=self.request.POST["board_id"])
        response = ScrabblyService().play(board, tiles, self.get_current_player())

        return self.json_response(response)


class RestartView(BaseBoardView):

    def post(self, *args, **kwargs):

        board_model = self.service.get(id=self.request.POST["board_id"])
        self.service.empty(board_model)

        return self.response("ok")

scrabbly_cloud/scrabblycloud/views/user.py
from base import BaseView
from scrabblycloud.services.facebook import FacebookService


class BaseUserView(BaseView):

    service = FacebookService()


class IndexView(BaseUserView):

    url = r"^$"

    def get(self, *args, **kwargs):

        return self.render_to_response({})


class FacebookLoginSuccessView(BaseUserView):

    template_name = "board/_user.html"

    def post(self, *args, **kwargs):

        user = self.service.save(self.request.POST["accessToken"], self.request)
        return self.json_response({"url": "/boards"});


class LogoutView(BaseUserView):

    def get(self, *args, **kwargs):

        self.service.logout(self.request)
        return self.redirect("/")

scrabbly_cloud/templates/board/_tile.html
<td id="box-{{x}}{{y}}" data-x="{{x}}" data-y="{{y}}" class="box {% if x == 7 and y == 7 %}central{% endif %}">
{% if letter %}
<div data-value="{{letter}}" class="tile">{{letter}}</div>
{% endif %}
</td>

scrabbly_cloud/templates/board/board.html
<html>
    <head>
        <link rel="stylesheet" href="/media/css/board.css">
        <script type='text/javascript' src='/media/js/jquery-1.7.1.min.js'></script>
        <script type='text/javascript' src='/media/js/redips-drag-min.js'></script>
        <script type="text/javascript" src="http://localhost:8080/application.js"></script>
        <script type="text/javascript">            

            function generateTile(letter) {
                var tile = $("<div>");
                tile.attr("data-value", letter);
                tile.addClass("tile");
                tile.text(letter);
                return tile;
            }

            function playEvent(data) {

                var data = JSON.parse(data);
                for (i in data.tiles) {
                    var box = $("#box-" + data.tiles[i].x + data.tiles[i].y);
                    if (box.children().length == 0) {
                        box.append(generateTile(data.tiles[i].letter));
                    } else {
                        box.children().first().removeClass("drag");
                        box.children()[0].onmousedown = null;
                    }
                }

                update_play_state(data);
            }

            try {
                var jug = new Juggernaut();
                jug.subscribe('play', playEvent);
            } catch(e) {
                console.log("Warning: Real Time module disabled");
            }

            /*var source = new EventSource('/board/update/');
            source.addEventListener('message', playEvent);*/

        </script>
        <script>
            var rd;

            $(document).ready(function() {
                rd = REDIPS.drag;
                rd.init('play-area');

                rd.drop_option = 'single';
            });

            function restart() {
                $.post("/board/restart/", {"board_id": "{{board.id}}"}, function() {
                    $("#board .tile").remove();
                });
            }

            function update_played_state(response) {

                $("#points-" + {{request.user.get_profile.remote_id}}).html(response.points);

                $("#next_player_name").html(response.next_player);
                $("#next_player").show();
                $("#play_button").hide();
            }

            function update_play_state(response) {

                $("#points-" + response.player).html(response.points);

                $("#play_button").show();
                $("#next_player").hide();                
            }

            function play() {

                var tiles = $("#board .drag");
                var letters = [];
                var boxes = [];
                tiles.each(function(k, v) {
                    var box = $(v);
                    obj = {
                        id: box.attr("data-id"),
                        x: box.parent().attr("data-x"),
                        y: box.parent().attr("data-y")
                    }
                    letters.push(obj);
                    boxes.push(box);
                })

                $.post("/board/play/", {letters: JSON.stringify(letters), "board_id": "{{board.id}}" }, function(response) {

                    var response = JSON.parse(response);

                    if (response.status == 'error') {
                        alert(response.message);
                    } else {
                        alert("Good move!");

                        update_played_state(response)

                        for (i in boxes) {
                            boxes[i].removeClass("drag");
                            boxes[i][0].onmousedown = null;
                        }
                    }
                });
            }
        </script>
    </head>

    <body>

        <div id="play-area">
            <div id="tiles-container" class="tiles-container">
                <table>
                    <tr>
                    {% for tile in player_board.tiles.all %}
                        <td><div data-id="{{tile.id}}" class="drag tile">{{tile.letter}}</div></td>
                    {% endfor %}
                    </tr>
                </table>
            </div>

            <div class="players">
            {% for player_board in board.playerboard_set.all %}
                <div><img src="{{player_board.player.picture}}">{{player_board.player.user.username}}: <span id="points-{{player_board.player.remote_id}}">{{player_board.points}}</span></div>
            {% endfor %}
            </div>

            
            <span id="play_button" class="{% if not is_player_turn %}hide{% endif %}">
                <button onclick="play()">Play!</button>
            </span>

            <span id="next_player" class="{% if is_player_turn %}hide{% endif %}">
                Wating for <span id="next_player_name">{{board.turn.user.username}}</span> to play...
            </span>

            <button onclick="restart()">Restart Game</button>

            <div id="board" class="board">
                <table>
                {% for row in tiles %}
                    <tr class="row">
                    {% for tile in row %}
                        {{tile|safe}}
                    {% endfor %}
                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>

    </body>
</html>

scrabbly_cloud/templates/board/boards.html
<html>

<head>
<script type='text/javascript' src='/media/js/jquery-1.7.1.min.js'></script>
<script type="text/javascript">

    function getLoginStatus(FB, callback) {

        FB.login(function(response) {

            saveFacebookUser(response.authResponse.accessToken, FB, callback);

        }, {scope: 'publish_stream, email'});
    }

    function saveFacebookUser(accessToken, user, callback, csrf_token) {

        $.post("/user/facebookloginsuccess/", {"accessToken": accessToken, "csrfmiddlewaretoken": "{{csrf_token}}" },
            function(html) {
                $("#user_bar").html(html);
            }
        );
    }

    window.fbAsyncInit = function() {

        FB.init({
            appId      : "{{FB_APP_ID}}",
            channelUrl : "{{HOST}}" + '/media/channel.html',
            status     : true,
            cookie     : true,
            xfbml      : true,
            oauth      : true
        });

    };

    (function(d){
        var js, id = 'facebook-jssdk';if (d.getElementById(id)) {return;}
        js = d.createElement('script');js.id = id;js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        d.getElementsByTagName('head')[0].appendChild(js);
    }(document));

</script>
</head>

<body>

<div id="user_bar">
{% if not request.user.is_authenticated %}
<button onclick="getLoginStatus(FB)">Facebook Login</button>
{% else %}
Hi {{request.user.username}} <img src="{{request.user.get_profile.picture}}">
{% endif %}
</div>

<h2>Select the board</h2>

<ul>
    {% for board in boards %}
        {% if board.players.count <= 2 %}
            <li><a href="/boards/{{board.id}}/">{{board.id}} 
            Players: 
            {% for player in board.players.all %}
                {% if not forloop.first %} - {% endif %}
                {{ player.user.username }}
            {% endfor %}
            </a></li>
        {% else %}
            <li>{{board.id}} 
            Players: 
            {% for player in board.players.all %}
                {% if not forloop.first %} - {% endif %}
                {{ player.user.username }}
            {% endfor %}
            </li>
        {% endif %}
    {% endfor %}
</ul>

</body>
</html>

scrabbly_cloud/templates/user/index.html
<html>

<head>
<script type='text/javascript' src='/media/js/jquery-1.7.1.min.js'></script>
<script type="text/javascript">

    function getLoginStatus(FB, callback) {

        FB.login(function(response) {

            saveFacebookUser(response.authResponse.accessToken, FB, callback);

        }, {scope: 'publish_stream, email'});
    }

    function saveFacebookUser(accessToken, user, callback, csrf_token) {

        $.post("/user/facebookloginsuccess/", {"accessToken": accessToken, "csrfmiddlewaretoken": "{{csrf_token}}" },
            function(response) {
                var response = JSON.parse(response);
                location.href = response.url;
            }
        );
    }

    window.fbAsyncInit = function() {

        FB.init({
            appId      : "{{FB_APP_ID}}",
            channelUrl : "{{HOST}}" + '/media/channel.html',
            status     : true,
            cookie     : true,
            xfbml      : true,
            oauth      : true
        });

    };

    (function(d){
        var js, id = 'facebook-jssdk';if (d.getElementById(id)) {return;}
        js = d.createElement('script');js.id = id;js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        d.getElementsByTagName('head')[0].appendChild(js);
    }(document));

</script>
</head>

<body>

<div id="user_bar">
<button onclick="getLoginStatus(FB)">Facebook Login</button>

</div>

</body>
</html>